INSERT INTO Category (id, name)
SELECT 1, 'Food' WHERE NOT EXISTS (SELECT 1 FROM Category WHERE id = 1)
UNION ALL
SELECT 2, 'Leisure' WHERE NOT EXISTS (SELECT 1 FROM Category WHERE id = 2)
UNION ALL
SELECT 3, 'Education' WHERE NOT EXISTS (SELECT 1 FROM Category WHERE id = 3)
UNION ALL
SELECT 4, 'Housing' WHERE NOT EXISTS (SELECT 1 FROM Category WHERE id = 4);

